<?php

return [
    // --- TOP TIER / FEATURED PROJECTS ---
    [
        'slug' => 'hostoo',
        'title' => 'Hostoo',
        'category' => 'Cloud & DevOps',
        'tags' => ['Laravel', 'GCP', 'CyberPanel', 'Billing'],
        'description' => 'Platform penyedia jasa hosting PHP otomatis yang terintegrasi langsung dengan Google Cloud Platform dan CyberPanel.',
        'image' => 'images/projects/hostoo.jpg',
        'featured' => true,
    ],
    [
        'slug' => 'skyflow',
        'title' => 'SkyFlow',
        'category' => 'Cloud & DevOps',
        'tags' => ['Nuxt.js', 'Go', 'Docker', 'PaaS'],
        'description' => 'Layanan deployment modern berbasis container (mirip Railway/Heroku) untuk berbagai bahasa pemrograman.',
        'image' => 'images/projects/skyflow.jpg',
        'featured' => true,
    ],
    [
        'slug' => 'kumbung-jamur',
        'title' => 'Kumbung Jamur IoT',
        'category' => 'IoT & Systems',
        'tags' => ['Next.js', 'IoT', 'MQTT', 'Real-time'],
        'description' => 'Dashboard monitoring suhu dan kelembaban kumbung jamur tiram, terintegrasi sensor IoT untuk pemantauan kondisi lingkungan budidaya.',
        'image' => 'images/projects/kumbung.jpg',
        'featured' => true,
    ],
    [
        'slug' => 'posify',
        'title' => 'Posify',
        'category' => 'Mobile App',
        'tags' => ['Flutter', 'Dart', 'API Integration'],
        'description' => 'Aplikasi mobile e-commerce makanan dengan UI/UX modern, mendukung manajemen keranjang dan tracking pesanan.',
        'image' => 'images/projects/posify.jpg',
        'featured' => true,
    ],

    // --- AI & RESEARCH ---
    [
        'slug' => 'hangeulvision',
        'title' => 'HangeulVision',
        'category' => 'AI & Data',
        'tags' => ['Django', 'Python', 'QCNN', 'Deep Learning', 'HTR'],
        'description' => 'Sistem Handwritten Text Recognition (HTR) untuk aksara Hangeul menggunakan model hybrid Quantum-Classical CNN dan ResNet-18.',
        'image' => 'images/projects/hangeulvision.jpg',
        'featured' => true,
    ],

    // --- SYSTEMS & APPLICATIONS ---
    [
        'slug' => 'isp-management',
        'title' => 'ISP Management System',
        'category' => 'Web App',
        'tags' => ['Next.js', 'Django REST', 'Billing'],
        'description' => 'Sistem manajemen pelanggan dan billing untuk penyedia layanan internet (ISP/RT RW Net).',
        'image' => 'images/projects/isp.jpg',
        'featured' => false,
    ],
    [
        'slug' => 'sikatup',
        'title' => 'Sikatup (PLN)',
        'category' => 'IoT & Systems',
        'tags' => ['Laravel', 'Monitoring', 'Enterprise'],
        'description' => 'Sistem monitoring kondisi Trafo untuk PT PLN guna mencegah kerusakan aset vital.',
        'image' => 'images/projects/sikatup.jpg',
        'featured' => false,
    ],
    [
        'slug' => 'swiftyle',
        'title' => 'Swiftyle',
        'category' => 'Mobile App',
        'tags' => ['Laravel', 'Ionic', 'E-commerce'],
        'description' => 'Platform fashion hybrid: Web Admin untuk penjual dan Mobile App (Ionic) untuk pembeli.',
        'image' => 'images/projects/swiftyle.jpg',
        'featured' => false,
    ],
    [
        'slug' => 'echolytics',
        'title' => 'Echolytics',
        'category' => 'AI & Data',
        'tags' => ['Django', 'Python', 'NLP', 'Crawling'],
        'description' => 'Tool analisis sentimen otomatis yang melakukan crawling komentar media sosial berdasarkan topik user.',
        'image' => 'images/projects/echolytics.jpg',
        'featured' => false,
    ],
    [
        'slug' => 'green-cold',
        'title' => 'Green Cold Products',
        'category' => 'Web App',
        'tags' => ['Laravel', 'QR Code', 'Inventory'],
        'description' => 'Manajemen inventaris dengan fitur generasi dan scan QR Code untuk label fisik barang.',
        'image' => 'images/projects/greencold.jpg',
        'featured' => false,
    ],
    [
        'slug' => 'certisend',
        'title' => 'Certisend',
        'category' => 'Tools',
        'tags' => ['Laravel', 'Automation', 'Mail'],
        'description' => 'Aplikasi pengirim sertifikat massal otomatis berbasis data Excel dan template PDF.',
        'image' => 'images/projects/certisend.jpg',
        'featured' => false,
    ],
    [
        'slug' => 'aurora',
        'title' => 'Aurora',
        'category' => 'Creative',
        'tags' => ['React.js', 'Canvas', 'Drawing'],
        'description' => 'Aplikasi sketchpad/drawing board berbasis web yang interaktif.',
        'image' => 'images/projects/aurora.jpg',
        'featured' => false,
    ],

    // --- INTERNSHIP & COMMUNITY ---
    [
        'slug' => 'cbi-portal-supplier',
        'title' => 'Portal Supplier (CBI)',
        'category' => 'Internship',
        'tags' => ['CodeIgniter 4', 'Enterprise'],
        'description' => 'Sistem manajemen supplier untuk PT Century Batteries Indonesia.',
        'image' => 'images/projects/cbi-supplier.jpg',
        'featured' => false,
    ],
    [
        'slug' => 'cbi-audit-vendor',
        'title' => 'Portal Audit Vendor (CBI)',
        'category' => 'Internship',
        'tags' => ['CodeIgniter 4', 'Audit'],
        'description' => 'Digitalisasi proses audit vendor eksternal perusahaan.',
        'image' => 'images/projects/cbi-audit.jpg',
        'featured' => false,
    ],
    [
        'slug' => 'web-desa-mekarjaya',
        'title' => 'Web Desa Mekarjaya',
        'category' => 'Community',
        'tags' => ['Laravel', 'Public Service'],
        'description' => 'Portal informasi desa dan layanan pengajuan surat online untuk warga (KKN 2025).',
        'image' => 'images/projects/desa.jpg',
        'featured' => false,
    ],
];
